// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString, RequiredParams } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'ko'

export type Locales =
	| 'ko'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 손​님
	 */
	DEFAULT_NAME: string
	/**
	 * 다​굴
	 */
	GAME_GANG_UP: string
	/**
	 * 헥​스​클​래​시
	 */
	GAME_HEXCLASH: string
	/**
	 * 스​네​이​크
	 */
	GAME_SNAKE: string
	/**
	 * 클​래​식
	 */
	MODE_CLASSIC: string
	/**
	 * 시​작​부​터​ ​각​자​ ​다​른​ ​총​.​ ​루​팅​ ​없​음​.
	 */
	MODE_CLASSIC_BLURB: string
	/**
	 * 무​기​ ​·​ ​단​발
	 */
	MODE_GUN_SEMI: string
	/**
	 * 전​원​ ​단​발​ ​권​총​.​ ​처​치​하​면​ ​총​을​ ​줍​는​다​.
	 */
	MODE_GUN_SEMI_BLURB: string
	/**
	 * 무​기​ ​·​ ​연​발
	 */
	MODE_GUN_AUTO: string
	/**
	 * 전​원​ ​연​발​ ​권​총​.​ ​처​치​하​면​ ​총​을​ ​줍​는​다​.
	 */
	MODE_GUN_AUTO_BLURB: string
	/**
	 * 아​이​템
	 */
	MODE_ITEM: string
	/**
	 * 총​은​ ​기​본​ ​권​총​ ​고​정​.​ ​메​드​킷​·​부​스​터​만​ ​줍​는​다​.
	 */
	MODE_ITEM_BLURB: string
	/**
	 * 합​본
	 */
	MODE_FULL: string
	/**
	 * 단​발​ ​권​총​ ​시​작​.​ ​총​과​ ​아​이​템​을​ ​같​이​ ​줍​는​다​.
	 */
	MODE_FULL_BLURB: string
	/**
	 * 일​반​전
	 */
	MODE_HEXCLASH_STANDARD: string
	/**
	 * 6​인​ ​헥​스​ ​타​일​ ​전​략​ ​대​전​.
	 */
	MODE_HEXCLASH_STANDARD_BLURB: string
	/**
	 * 클​래​식
	 */
	MODE_SNAKE_CLASSIC: string
	/**
	 * 4​인​ ​스​네​이​크​ ​서​바​이​벌​.
	 */
	MODE_SNAKE_CLASSIC_BLURB: string
	/**
	 * 방​을​ ​찾​을​ ​수​ ​없​습​니​다
	 */
	ROOM_NOT_FOUND: string
	/**
	 * 방​이​ ​가​득​ ​찼​습​니​다​ ​(​8​)
	 */
	ROOM_FULL: string
	/**
	 * 지​금​은​ ​게​임​을​ ​바​꿀​ ​수​ ​없​습​니​다
	 */
	CANNOT_CHANGE_MODE: string
	/**
	 * 호​스​트​만​ ​게​임​을​ ​바​꿀​ ​수​ ​있​습​니​다
	 */
	HOST_ONLY_MODE: string
	/**
	 * 호​스​트​만​ ​시​작​할​ ​수​ ​있​습​니​다
	 */
	HOST_ONLY_START: string
	/**
	 * 지​금​은​ ​내​보​낼​ ​수​ ​없​습​니​다
	 */
	CANNOT_KICK: string
	/**
	 * 호​스​트​만​ ​내​보​낼​ ​수​ ​있​습​니​다
	 */
	HOST_ONLY_KICK: string
	/**
	 * 호​스​트​가​ ​방​에​서​ ​내​보​냈​습​니​다​.
	 */
	KICKED_MSG: string
	/**
	 * 호​스​트​가​ ​게​임​을​ ​시​작​하​지​ ​못​했​습​니​다​.
	 */
	HOST_BOOT_FAIL: string
	/**
	 * 게​임​이​ ​끝​났​습​니​다​.​ ​대​기​실​로​ ​돌​아​왔​습​니​다​.
	 */
	GAME_END_LOBBY: string
	/**
	 * 이​전​ ​자​리​를​ ​찾​지​ ​못​했​습​니​다​.​ ​로​비​로​ ​갑​니​다​.
	 */
	RESUME_NOT_FOUND: string
	/**
	 * {​n​a​m​e​}​ ​이​(​가​)​ ​들​어​왔​습​니​다​.
	 * @param {string} name
	 */
	playerJoined: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​이​(​가​)​ ​내​보​내​졌​습​니​다​.
	 * @param {string} name
	 */
	playerKicked: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​이​(​가​)​ ​나​갔​습​니​다​.
	 * @param {string} name
	 */
	playerLeft: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​이​(​가​)​ ​다​시​ ​연​결​되​었​습​니​다​.
	 * @param {string} name
	 */
	playerReconnected: RequiredParams<'name'>
	/**
	 * 호​스​트​(​{​n​a​m​e​}​)​가​ ​나​가​서​ ​게​임​이​ ​종​료​됩​니​다​.
	 * @param {string} name
	 */
	hostLeftEnd: RequiredParams<'name'>
	/**
	 * 호​스​트​(​{​n​a​m​e​}​)​의​ ​연​결​이​ ​끊​겨​ ​게​임​이​ ​종​료​됩​니​다​.
	 * @param {string} name
	 */
	hostDisconnectedEnd: RequiredParams<'name'>
	/**
	 * {​n​a​m​e​}​ ​연​결​이​ ​끊​겼​습​니​다​.​ ​{​s​e​c​}​초​ ​안​에​ ​다​시​ ​들​어​오​면​ ​자​리​가​ ​유​지​됩​니​다​.
	 * @param {string} name
	 * @param {number} sec
	 */
	playerDropped: RequiredParams<'name' | 'sec'>
}

export type TranslationFunctions = {
	/**
	 * 손님
	 */
	DEFAULT_NAME: () => LocalizedString
	/**
	 * 다굴
	 */
	GAME_GANG_UP: () => LocalizedString
	/**
	 * 헥스클래시
	 */
	GAME_HEXCLASH: () => LocalizedString
	/**
	 * 스네이크
	 */
	GAME_SNAKE: () => LocalizedString
	/**
	 * 클래식
	 */
	MODE_CLASSIC: () => LocalizedString
	/**
	 * 시작부터 각자 다른 총. 루팅 없음.
	 */
	MODE_CLASSIC_BLURB: () => LocalizedString
	/**
	 * 무기 · 단발
	 */
	MODE_GUN_SEMI: () => LocalizedString
	/**
	 * 전원 단발 권총. 처치하면 총을 줍는다.
	 */
	MODE_GUN_SEMI_BLURB: () => LocalizedString
	/**
	 * 무기 · 연발
	 */
	MODE_GUN_AUTO: () => LocalizedString
	/**
	 * 전원 연발 권총. 처치하면 총을 줍는다.
	 */
	MODE_GUN_AUTO_BLURB: () => LocalizedString
	/**
	 * 아이템
	 */
	MODE_ITEM: () => LocalizedString
	/**
	 * 총은 기본 권총 고정. 메드킷·부스터만 줍는다.
	 */
	MODE_ITEM_BLURB: () => LocalizedString
	/**
	 * 합본
	 */
	MODE_FULL: () => LocalizedString
	/**
	 * 단발 권총 시작. 총과 아이템을 같이 줍는다.
	 */
	MODE_FULL_BLURB: () => LocalizedString
	/**
	 * 일반전
	 */
	MODE_HEXCLASH_STANDARD: () => LocalizedString
	/**
	 * 6인 헥스 타일 전략 대전.
	 */
	MODE_HEXCLASH_STANDARD_BLURB: () => LocalizedString
	/**
	 * 클래식
	 */
	MODE_SNAKE_CLASSIC: () => LocalizedString
	/**
	 * 4인 스네이크 서바이벌.
	 */
	MODE_SNAKE_CLASSIC_BLURB: () => LocalizedString
	/**
	 * 방을 찾을 수 없습니다
	 */
	ROOM_NOT_FOUND: () => LocalizedString
	/**
	 * 방이 가득 찼습니다 (8)
	 */
	ROOM_FULL: () => LocalizedString
	/**
	 * 지금은 게임을 바꿀 수 없습니다
	 */
	CANNOT_CHANGE_MODE: () => LocalizedString
	/**
	 * 호스트만 게임을 바꿀 수 있습니다
	 */
	HOST_ONLY_MODE: () => LocalizedString
	/**
	 * 호스트만 시작할 수 있습니다
	 */
	HOST_ONLY_START: () => LocalizedString
	/**
	 * 지금은 내보낼 수 없습니다
	 */
	CANNOT_KICK: () => LocalizedString
	/**
	 * 호스트만 내보낼 수 있습니다
	 */
	HOST_ONLY_KICK: () => LocalizedString
	/**
	 * 호스트가 방에서 내보냈습니다.
	 */
	KICKED_MSG: () => LocalizedString
	/**
	 * 호스트가 게임을 시작하지 못했습니다.
	 */
	HOST_BOOT_FAIL: () => LocalizedString
	/**
	 * 게임이 끝났습니다. 대기실로 돌아왔습니다.
	 */
	GAME_END_LOBBY: () => LocalizedString
	/**
	 * 이전 자리를 찾지 못했습니다. 로비로 갑니다.
	 */
	RESUME_NOT_FOUND: () => LocalizedString
	/**
	 * {name} 이(가) 들어왔습니다.
	 */
	playerJoined: (arg: { name: string }) => LocalizedString
	/**
	 * {name} 이(가) 내보내졌습니다.
	 */
	playerKicked: (arg: { name: string }) => LocalizedString
	/**
	 * {name} 이(가) 나갔습니다.
	 */
	playerLeft: (arg: { name: string }) => LocalizedString
	/**
	 * {name} 이(가) 다시 연결되었습니다.
	 */
	playerReconnected: (arg: { name: string }) => LocalizedString
	/**
	 * 호스트({name})가 나가서 게임이 종료됩니다.
	 */
	hostLeftEnd: (arg: { name: string }) => LocalizedString
	/**
	 * 호스트({name})의 연결이 끊겨 게임이 종료됩니다.
	 */
	hostDisconnectedEnd: (arg: { name: string }) => LocalizedString
	/**
	 * {name} 연결이 끊겼습니다. {sec}초 안에 다시 들어오면 자리가 유지됩니다.
	 */
	playerDropped: (arg: { name: string, sec: number }) => LocalizedString
}

export type Formatters = {}
