import { ArraySchema, Schema, type } from "@colyseus/schema";
import { MatchCloneSchema } from "./clone.js";
import { MatchHeroHudSchema } from "./hero-hud.js";
import { MatchTimedBuffSchema } from "./timed-buff.js";

/** packAuthoritySnap SnapPlayer 와 같은 필드. */
export class MatchHeroSchema extends Schema {
  @type("int8") slot = -1;
  @type("string") name = "";
  @type("float32") x = 0;
  @type("float32") y = 0;
  @type("float32") aimX = 0;
  @type("float32") aimY = 0;
  @type("float32") hp = 0;
  @type("float32") maxHp = 0;
  @type("boolean") alive = true;
  @type("uint8") mag = 0;
  @type("uint8") magMax = 0;
  @type("float32") reloadLeft = 0;
  @type("string") weapon = "";
  @type("float32") ult = 0;
  @type("uint32") ack = 0;
  @type("int8") animal = -1;
  @type("string") characterId = "";
  @type("boolean") cpu = false;
  /** packItemStack SSOT — '' | kind | kind:N. 메드킷은 packItemField. */
  @type("string") item = "";
  @type("uint32") kills = 0;
  @type("boolean") downed = false;
  @type("float32") downLeft = 0;
  @type("uint32") deaths = 0;
  @type("float32") score = 0;
  @type("uint32") streak = 0;
  @type("int8") emote = -1;
  @type("float32") emoteTime = 0;
  @type("string") weaponId = "";
  @type("float32") stunTime = 0;
  @type("float32") rootTime = 0;
  @type("float32") ccTime = 0;
  @type("float32") guardTime = 0;
  @type("float32") armorTime = 0;
  @type("float32") spawnProtect = 0;
  @type("float32") launchTime = 0;
  @type("float32") launchVX = 0;
  @type("float32") launchVY = 0;
  @type("boolean") charging = false;
  @type("float32") chargeTime = 0;
  @type("float32") dmgOrbTime = 0;
  @type("float32") downTaken = 0;
  @type("float32") woolTime = 0;
  @type("int16") woolHp = 0;
  @type("int16") woolMax = 0;
  @type("float32") rouletteTime = 0;
  @type("string") rouletteRank = "";
  @type("string") roulettePhase = "";
  @type("string") rouletteSpin = "";
  @type("string") rouletteLabel = "";
  @type("string") action = "";
  @type("string") heldItem = "";
  @type("float32") springTime = 0;
  @type("float32") slideTime = 0;
  @type([MatchTimedBuffSchema]) timedBuffs = new ArraySchema<MatchTimedBuffSchema>();
  @type([MatchCloneSchema]) clones = new ArraySchema<MatchCloneSchema>();
  @type("boolean") parked = false;
  @type("float32") pullTime = 0;
  @type("float32") pocketTime = 0;
  @type("float32") hopTime = 0;
  @type("float32") hopMax = 0;
  @type("float32") hopHeight = 0;
  @type("float32") mobilityCd = 0;
  @type(MatchHeroHudSchema) hud = new MatchHeroHudSchema();
}
