class_name HudStrings
extends RefCounted
## 인게임 HUD i18n 번역 테이블. React(next-intl)의 locale을 sessionStorage로 받는다.

static var _locale := "ko"

const STRINGS := {
    "ko": {
        "zodiac_0": "쥐", "zodiac_1": "소", "zodiac_2": "호랑이", "zodiac_3": "토끼",
        "zodiac_4": "용", "zodiac_5": "뱀", "zodiac_6": "말", "zodiac_7": "양",
        "zodiac_8": "원숭이", "zodiac_9": "닭", "zodiac_10": "개", "zodiac_11": "돼지",
        "zone_shrinking": "안전 구역 축소 중",
        "zone_final": "최종 안전 구역",
        "zone_countdown": "축소까지 %d초",
        "touch_fire": "공격", "touch_medkit": "약", "touch_dash": "대시",
        "spectate_eliminated": "탈락 - 관전 중",
        "spectate_respawning": "부활 대기 중 - 관전 중",
        "spectate_info": "관전 P%d %s / %s",
        "spectate_controls": "A/D 또는 TAB: 관전 대상 변경  |  SPACE: 1위 자동 추적",
        "countdown_ready": "준비",
        "result_returning": "지금 대기실로 이동합니다",
        "result_countdown": "%d초 후 대기실로 이동합니다",
        "result_rematch": "R  재경기    ·    ESC  나가기",
        "default_name": "플레이어",
        "downed_by": "P%d %s님이 쓰러졌습니다.",
        "eliminated_label": "%s 탈락",
        "eliminated_suffix": " 제거",
        "buff_atk": "이번 목숨 동안 공격력이 올라갑니다",
        "buff_spd": "이번 목숨 동안 이동속도가 빨라집니다",
        "buff_def": "받는 피해가 줄어듭니다",
        "buff_hp": "최대 체력과 현재 체력이 늘어납니다",
        "buff_rate": "연사 속도가 빨라집니다",
        "buff_range": "총알이 더 멀리 나갑니다",
        "buff_giant": "몸이 커지고 공격과 이동이 세집니다",
        "buff_double_giant": "더 크게 변하고 능력치가 크게 오릅니다",
        "buff_shield": "잠시 보호막이 생깁니다",
        "buff_berserk": "공격과 연사가 잠깐 폭주합니다",
        "buff_sniper": "사거리가 늘어나고 한 방이 세집니다",
        "buff_turtle": "2초 동안 공격과 대시를 쓸 수 없습니다",
        "buff_default": "효과를 얻었습니다",
        "hint_hit": "피격! Shift로 대시해서 벗어나세요",
        "hint_down": "다운! %s%s%s%s 자리로 기어가세요. 곧 부활합니다",
        "hint_outside_zone": "세이프존 밖! 안쪽으로 이동하세요",
        "hint_ultimate_ready": "궁극기 준비! %s를 누르세요",
        "settings_title": "설정",
        "settings_controls": "조작 방식",
        "settings_sound": "소리",
        "settings_sound_on": "효과음 켜기",
        "settings_close": "닫기",
        "settings_leave": "로비로 나가기",
        "mode_keyboard": "PC 키보드형",
        "mode_touch": "모바일형",
        "mode_auto": "자동",
        "mode_keyboard_desc": "WASD 이동 · 마우스 조준 · 가상 스틱/버튼 숨김",
        "mode_touch_desc": "화면 스틱/버튼 항상 표시 · 키보드도 함께 사용 가능",
        "mode_auto_desc": "기기에 맞춰 결정 (모바일·거친 포인터면 모바일형)",
        "btn_exit": "나가기",
        "btn_rematch": "재경기",
        "btn_to_lobby": "대기실로",
        "weapon_default": "권총",
        "flee_marker": "도망",
        "snake_shed_label": "허물",
        "streak_prefix": "x%d 연속",
        "hud_hp": "체력  %d / %d",
        "hud_ult_ready": "궁 준비",
        "hud_ult_pct": "궁  %d%%",
        "hud_kills": "처치  %d",
        "hud_alive": "생존  %d / %d",
        "hud_ammo": "탄약  %d / %d",
        "hud_reload": "재장전  %d / %d",
        "hud_reload_name": "재장전",
        "hud_reload_time": "재장전 %.1f초",
        "hud_empty": "빔  0 / %d",
        "hud_lives": "%d명 남음",
        "hud_out": "탈락",
        "hud_down_finish": "다운 %.1f   처형 %d/48",
        "hud_respawn": "부활 %.1f",
        "hud_wanted": "현상수배 P%d  %s",
        "hud_stunned": "기절  |  조작 잠김",
        "hud_rooted": "속박  |  이동·대시·점프 잠김, 사격은 가능",
        "hud_ready": "준비",
        "hud_key_lmb": "좌클릭",
        "hud_key_rmb": "우클릭",
        "hud_f1": "F1  HUD",
        "hud_scoreboard": "실시간 순위  캐릭터 / 총            점수  처치/사망  존  상태",
        "state_live": "생존",
        "state_out": "탈락",
        "state_wait": "대기",
        "state_stun": "기절",
        "state_root": "속박",
        "state_cc": "군중제어",
        "state_live_streak": "생존 x%d",
        "match_draw": "무승부",
        "match_no_survivors": "생존자 없음",
        "match_winner": "승리",
        "match_standings": "최종 순위",
        "stat_hp_pct": "체력  %d%%",
        "stat_zone": "존  %d",
        "stat_score": "점수  %d",
        "chip_atk": "공",
        "chip_spd": "속",
        "chip_def": "방",
        "chip_hp": "체",
        "chip_rate": "연사",
        "chip_range": "사거리",
        "chip_dmg": "피해",
        "chip_safe": "보호",
        "chip_ice": "얼음",
        "chip_zone": "구역",
        "chip_hop": "점프",
        "chip_buff": "버프",
        "item_medkit": "치료",
        "item_spring": "스프링",
        "item_slide": "슬라이드",
        "item_pull": "당기기",
        "item_pocket": "주머니",
        "item_decoy": "미끼",
        "item_empty": "없음",
        "item_default": "없음",
        "ult_0": "조류",
        "ult_1": "들이받기",
        "ult_2": "포효",
        "ult_3": "굴",
        "ult_4": "연기",
        "ult_5": "허물",
        "ult_6": "뒷발",
        "ult_7": "털방패",
        "ult_8": "분신",
        "ult_9": "알",
        "ult_10": "뼈돌진",
        "ult_11": "진흙",
        "skill_scatter": "후폭풍",
        "skill_rail": "고정 파괴",
        "skill_mortar": "낙하포",
        "skill_leech": "피의 작살",
        "skill_breaker": "돌파",
        "skill_burst": "유도탄",
        "skill_blade": "횡단베기",
        "skill_brawler": "급소타격",
        "skill_bomb": "근접지뢰",
        "skill_spear": "창 돌진",
        "skill_chain": "사슬속박",
        "skill_shield": "불도저 벽",
        "skill_default": "장비 스킬",
        "mobility_scatter": "견제점프",
        "mobility_rail": "조준이동",
        "mobility_mortar": "폭약점프",
        "mobility_leech": "그림자끌기",
        "mobility_breaker": "철갑전진",
        "mobility_burst": "점멸베기",
        "mobility_blade": "그림자숨",
        "mobility_brawler": "빗겨서기",
        "mobility_bomb": "구르기",
        "mobility_spear": "장대점프",
        "mobility_chain": "선회",
        "mobility_shield": "가드스텝",
        "mobility_default": "대시",
        "special_scatter": "경량",
        "special_rail": "경량",
        "special_mortar": "유리체",
        "special_leech": "중형",
        "special_breaker": "중량",
        "special_burst": "경량",
        "special_blade": "경속",
        "special_brawler": "역전",
        "special_bomb": "중형",
        "special_spear": "탱커",
        "special_chain": "중형",
        "special_shield": "중량",
        "special_default": "기본",
    },
    "en": {
        "zodiac_0": "Rat", "zodiac_1": "Ox", "zodiac_2": "Tiger", "zodiac_3": "Rabbit",
        "zodiac_4": "Dragon", "zodiac_5": "Snake", "zodiac_6": "Horse", "zodiac_7": "Goat",
        "zodiac_8": "Monkey", "zodiac_9": "Rooster", "zodiac_10": "Dog", "zodiac_11": "Pig",
        "zone_shrinking": "Zone shrinking",
        "zone_final": "Final zone",
        "zone_countdown": "Shrink in %ds",
        "touch_fire": "Fire", "touch_medkit": "Med", "touch_dash": "Dash",
        "spectate_eliminated": "Eliminated - Spectating",
        "spectate_respawning": "Respawning - Spectating",
        "spectate_info": "Spectating P%d %s / %s",
        "spectate_controls": "A/D or TAB: Switch target  |  SPACE: Follow #1",
        "countdown_ready": "GET READY",
        "result_returning": "Returning to the waiting room now",
        "result_countdown": "Returning to the waiting room in %ds",
        "result_rematch": "R  Rematch    ·    ESC  Quit",
        "default_name": "Player",
        "downed_by": "P%d %s went down.",
        "eliminated_label": "%s eliminated",
        "eliminated_suffix": " finished",
        "buff_atk": "Attack power increased for this life",
        "buff_spd": "Movement speed increased for this life",
        "buff_def": "Damage taken reduced",
        "buff_hp": "Max HP and current HP increased",
        "buff_rate": "Fire rate increased",
        "buff_range": "Bullets travel farther",
        "buff_giant": "Grow bigger with boosted attack and speed",
        "buff_double_giant": "Grow even bigger with greatly boosted stats",
        "buff_shield": "Temporary shield activated",
        "buff_berserk": "Attack and fire rate go berserk",
        "buff_sniper": "Range extended, damage increased",
        "buff_turtle": "Cannot attack or dash for 2 seconds",
        "buff_default": "Buff activated",
        "hint_hit": "Hit! Dash with Shift to escape",
        "hint_down": "Down! Crawl with %s%s%s%s. Respawning soon",
        "hint_outside_zone": "Outside zone! Move inside",
        "hint_ultimate_ready": "Ultimate ready! Press %s",
        "settings_title": "Settings",
        "settings_controls": "Controls",
        "settings_sound": "Sound",
        "settings_sound_on": "Sound effects",
        "settings_close": "Close",
        "settings_leave": "Leave to lobby",
        "mode_keyboard": "PC Keyboard",
        "mode_touch": "Mobile",
        "mode_auto": "Auto",
        "mode_keyboard_desc": "WASD move · mouse aim · virtual pad hidden",
        "mode_touch_desc": "On-screen pad always shown · keyboard also works",
        "mode_auto_desc": "Auto-detect (mobile/coarse pointer → mobile mode)",
        "btn_exit": "Exit",
        "btn_rematch": "Rematch",
        "btn_to_lobby": "To Lobby",
        "weapon_default": "Pistol",
        "flee_marker": "Flee",
        "snake_shed_label": "Shed",
        "streak_prefix": "x%d streak",
        "hud_hp": "HP  %d / %d",
        "hud_ult_ready": "ULT READY",
        "hud_ult_pct": "ULT  %d%%",
        "hud_kills": "KILLS  %d",
        "hud_alive": "ALIVE  %d / %d",
        "hud_ammo": "AMMO  %d / %d",
        "hud_reload": "RELOAD  %d / %d",
        "hud_reload_name": "Reload",
        "hud_reload_time": "Reload %.1fs",
        "hud_empty": "EMPTY  0 / %d",
        "hud_lives": "%d LEFT",
        "hud_out": "OUT",
        "hud_down_finish": "DOWN %.1f   FINISH %d/48",
        "hud_respawn": "RESPAWN %.1f",
        "hud_wanted": "WANTED P%d  %s",
        "hud_stunned": "STUNNED  |  INPUT LOCKED",
        "hud_rooted": "ROOTED  |  MOVE/DASH/JUMP LOCKED, FIRE OK",
        "hud_ready": "READY",
        "hud_key_lmb": "LMB",
        "hud_key_rmb": "RMB",
        "hud_f1": "F1  HUD",
        "hud_scoreboard": "LIVE RANK  CHARACTER / GUN            SCORE  D/D  ZONE  STATE",
        "state_live": "LIVE",
        "state_out": "OUT",
        "state_wait": "WAIT",
        "state_stun": "STUN",
        "state_root": "ROOT",
        "state_cc": "CC",
        "state_live_streak": "LIVE x%d",
        "match_draw": "MATCH DRAW",
        "match_no_survivors": "NO SURVIVORS",
        "match_winner": "MATCH WINNER",
        "match_standings": "FINAL STANDINGS",
        "stat_hp_pct": "HP  %d%%",
        "stat_zone": "ZONE  %d",
        "stat_score": "SCORE  %d",
        "chip_atk": "ATK",
        "chip_spd": "SPD",
        "chip_def": "DEF",
        "chip_hp": "HP",
        "chip_rate": "RATE",
        "chip_range": "RNG",
        "chip_dmg": "DMG",
        "chip_safe": "SAFE",
        "chip_ice": "ICE",
        "chip_zone": "ZONE",
        "chip_hop": "HOP",
        "chip_buff": "BUFF",
        "item_medkit": "MEDKIT",
        "item_spring": "SPRING",
        "item_slide": "SLIDE",
        "item_pull": "PULL",
        "item_pocket": "POCKET",
        "item_decoy": "DECOY",
        "item_empty": "EMPTY",
        "item_default": "EMPTY",
        "ult_0": "Tide",
        "ult_1": "Gore",
        "ult_2": "Roar",
        "ult_3": "Burrow",
        "ult_4": "Smoke",
        "ult_5": "Shed",
        "ult_6": "Kick",
        "ult_7": "Wool",
        "ult_8": "Mirage",
        "ult_9": "Egg",
        "ult_10": "Fetch",
        "ult_11": "Mud",
        "skill_scatter": "Backblast",
        "skill_rail": "Anchor Break",
        "skill_mortar": "Skyfall",
        "skill_leech": "Blood Harpoon",
        "skill_breaker": "Crash Entry",
        "skill_burst": "Seeker Salvo",
        "skill_blade": "Cross Step",
        "skill_brawler": "Liver Shot",
        "skill_bomb": "Prox Mine",
        "skill_spear": "Vault Impale",
        "skill_chain": "Chain Lock",
        "skill_shield": "Bulldozer Wall",
        "skill_default": "Weapon Skill",
        "mobility_scatter": "Skirmish Hop",
        "mobility_rail": "Sightline Step",
        "mobility_mortar": "Blast Hop",
        "mobility_leech": "Shadow Pull",
        "mobility_breaker": "Iron March",
        "mobility_burst": "Flash Cut",
        "mobility_blade": "Shadow Sheath",
        "mobility_brawler": "Weave",
        "mobility_bomb": "Blast Roll",
        "mobility_spear": "Pole Vault",
        "mobility_chain": "Swing Step",
        "mobility_shield": "Brace Step",
        "mobility_default": "Dash",
        "special_scatter": "Light",
        "special_rail": "Light",
        "special_mortar": "Glass",
        "special_leech": "Mid",
        "special_breaker": "Heavy",
        "special_burst": "Light",
        "special_blade": "Swift",
        "special_brawler": "Comeback",
        "special_bomb": "Mid",
        "special_spear": "Tank",
        "special_chain": "Mid",
        "special_shield": "Heavy",
        "special_default": "Base",
    },
}

static func set_locale(locale: String) -> void:
    _locale = locale if STRINGS.has(locale) else "ko"

static func get_locale() -> String:
    return _locale

static func t(key: String) -> String:
    var table: Dictionary = STRINGS.get(_locale, STRINGS["ko"])
    return str(table.get(key, key))

static func zodiac(index: int) -> String:
    return t("zodiac_%d" % posmod(index, CharacterCatalog.bind_count("animal")))

static func named(prefix: String, id: String) -> String:
    var key := "%s_%s" % [prefix, id]
    var table: Dictionary = STRINGS.get(_locale, STRINGS["ko"])
    if table.has(key):
        return str(table[key])
    return t("%s_default" % prefix)

static func skill(equip_id: String) -> String:
    return named("skill", equip_id)

static func mobility(equip_id: String) -> String:
    return named("mobility", equip_id)

static func special(equip_id: String) -> String:
    return named("special", equip_id)

static func animal_ult(animal: int) -> String:
    return t("ult_%d" % posmod(animal, CharacterCatalog.bind_count("animal")))

static func item(kind: String) -> String:
    return named("item", kind)
