class_name HudStrings
extends RefCounted
## 인게임 HUD i18n 번역 테이블. React(next-intl)의 locale을 sessionStorage로 받는다.

static var _locale := "ko"

const STRINGS := {
    "ko": {
        "zodiac_0": "쥐", "zodiac_1": "소", "zodiac_2": "호랑이", "zodiac_3": "토끼",
        "zodiac_4": "용", "zodiac_5": "뱀", "zodiac_6": "말", "zodiac_7": "양",
        "zodiac_8": "원숭이", "zodiac_9": "닭", "zodiac_10": "개", "zodiac_11": "돼지",
        "zone_shrinking": "안전 구역 축소 중",
        "zone_final": "최종 안전 구역",
        "zone_countdown": "축소까지 %d초",
        "touch_fire": "공격", "touch_medkit": "약", "touch_dash": "대시",
        "spectate_eliminated": "탈락 - 관전 중",
        "spectate_respawning": "부활 대기 중 - 관전 중",
        "spectate_info": "관전 P%d %s / %s",
        "spectate_controls": "A/D 또는 TAB: 관전 대상 변경  |  SPACE: 1위 자동 추적",
        "result_returning": "대기실로 이동 중",
        "result_countdown": "%d초 후 대기실",
        "result_rematch": "R  재경기    ·    ESC  나가기",
        "default_name": "플레이어",
        "downed_by": "P%d %s님이 쓰러졌습니다.",
        "eliminated_label": "%s 탈락",
        "eliminated_suffix": " 제거",
        "buff_atk": "이번 목숨 동안 공격력이 올라갑니다",
        "buff_spd": "이번 목숨 동안 이동속도가 빨라집니다",
        "buff_def": "받는 피해가 줄어듭니다",
        "buff_hp": "최대 체력과 현재 체력이 늘어납니다",
        "buff_rate": "연사 속도가 빨라집니다",
        "buff_range": "총알이 더 멀리 나갑니다",
        "buff_giant": "몸이 커지고 공격과 이동이 세집니다",
        "buff_double_giant": "더 크게 변하고 능력치가 크게 오릅니다",
        "buff_shield": "잠시 보호막이 생깁니다",
        "buff_berserk": "공격과 연사가 잠깐 폭주합니다",
        "buff_sniper": "사거리가 늘어나고 한 방이 세집니다",
        "buff_turtle": "2초 동안 공격과 대시를 쓸 수 없습니다",
        "buff_default": "효과를 얻었습니다",
        "hint_hit": "피격! Shift로 대시해서 벗어나세요",
        "hint_down": "다운! %s%s%s%s 자리로 기어가세요. 곧 부활합니다",
        "hint_outside_zone": "세이프존 밖! 안쪽으로 이동하세요",
        "hint_ultimate_ready": "궁극기 준비! %s를 누르세요",
        "settings_title": "설정",
        "settings_controls": "조작 방식",
        "settings_sound": "소리",
        "settings_sound_on": "효과음 켜기",
        "settings_close": "닫기",
        "settings_leave": "로비로 나가기",
        "mode_keyboard": "PC 키보드형",
        "mode_touch": "모바일형",
        "mode_auto": "자동",
        "mode_keyboard_desc": "WASD 이동 · 마우스 조준 · 가상 스틱/버튼 숨김",
        "mode_touch_desc": "화면 스틱/버튼 항상 표시 · 키보드도 함께 사용 가능",
        "mode_auto_desc": "기기에 맞춰 결정 (모바일·거친 포인터면 모바일형)",
        "btn_exit": "나가기",
        "btn_rematch": "재경기",
        "btn_to_lobby": "대기실로",
        "weapon_default": "권총",
        "flee_marker": "도망",
        "snake_shed_label": "허물",
        "streak_prefix": "x%d 연속",
    },
    "en": {
        "zodiac_0": "Rat", "zodiac_1": "Ox", "zodiac_2": "Tiger", "zodiac_3": "Rabbit",
        "zodiac_4": "Dragon", "zodiac_5": "Snake", "zodiac_6": "Horse", "zodiac_7": "Goat",
        "zodiac_8": "Monkey", "zodiac_9": "Rooster", "zodiac_10": "Dog", "zodiac_11": "Pig",
        "zone_shrinking": "Zone shrinking",
        "zone_final": "Final zone",
        "zone_countdown": "Shrink in %ds",
        "touch_fire": "Fire", "touch_medkit": "Med", "touch_dash": "Dash",
        "spectate_eliminated": "Eliminated - Spectating",
        "spectate_respawning": "Respawning - Spectating",
        "spectate_info": "Spectating P%d %s / %s",
        "spectate_controls": "A/D or TAB: Switch target  |  SPACE: Follow #1",
        "result_returning": "Returning to lobby",
        "result_countdown": "Lobby in %ds",
        "result_rematch": "R  Rematch    ·    ESC  Quit",
        "default_name": "Player",
        "downed_by": "P%d %s went down.",
        "eliminated_label": "%s eliminated",
        "eliminated_suffix": " finished",
        "buff_atk": "Attack power increased for this life",
        "buff_spd": "Movement speed increased for this life",
        "buff_def": "Damage taken reduced",
        "buff_hp": "Max HP and current HP increased",
        "buff_rate": "Fire rate increased",
        "buff_range": "Bullets travel farther",
        "buff_giant": "Grow bigger with boosted attack and speed",
        "buff_double_giant": "Grow even bigger with greatly boosted stats",
        "buff_shield": "Temporary shield activated",
        "buff_berserk": "Attack and fire rate go berserk",
        "buff_sniper": "Range extended, damage increased",
        "buff_turtle": "Cannot attack or dash for 2 seconds",
        "buff_default": "Buff activated",
        "hint_hit": "Hit! Dash with Shift to escape",
        "hint_down": "Down! Crawl with %s%s%s%s. Respawning soon",
        "hint_outside_zone": "Outside zone! Move inside",
        "hint_ultimate_ready": "Ultimate ready! Press %s",
        "settings_title": "Settings",
        "settings_controls": "Controls",
        "settings_sound": "Sound",
        "settings_sound_on": "Sound effects",
        "settings_close": "Close",
        "settings_leave": "Leave to lobby",
        "mode_keyboard": "PC Keyboard",
        "mode_touch": "Mobile",
        "mode_auto": "Auto",
        "mode_keyboard_desc": "WASD move · mouse aim · virtual pad hidden",
        "mode_touch_desc": "On-screen pad always shown · keyboard also works",
        "mode_auto_desc": "Auto-detect (mobile/coarse pointer → mobile mode)",
        "btn_exit": "Exit",
        "btn_rematch": "Rematch",
        "btn_to_lobby": "To Lobby",
        "weapon_default": "Pistol",
        "flee_marker": "Flee",
        "snake_shed_label": "Shed",
        "streak_prefix": "x%d streak",
    },
}

static func set_locale(locale: String) -> void:
    _locale = locale if STRINGS.has(locale) else "ko"

static func get_locale() -> String:
    return _locale

static func t(key: String) -> String:
    var table: Dictionary = STRINGS.get(_locale, STRINGS["ko"])
    return str(table.get(key, key))

static func zodiac(index: int) -> String:
    return t("zodiac_%d" % posmod(index, 12))
