import { chromium } from "playwright-core";
const exe = process.env.CHROME_PATH || "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome";
const browser = await chromium.launch({ headless: true, executablePath: exe });
const page = await browser.newPage({ viewport: { width: 480, height: 800 } });
await page.goto("http://127.0.0.1:3000/", { waitUntil: "domcontentloaded" });
await page.locator(".name-input").fill("UI체크");
await page.locator(".cta").click();
await page.waitForTimeout(3000);
await page.screenshot({ path: "/tmp/lobby.png", fullPage: false });
await browser.close();
